- name: Install PIP3
  apt:
    name: python3-pip
    state: present

- name: Install psutil
  pip:
    name: psutil

- name: install statistics gathering software
  apt:
    pkg:
    - acct

- name: Download anydesk deb 
  get_url: 
    url="https://download.anydesk.com/rpi/anydesk_6.0.1-1_armhf.deb"
    dest="/home/{{ ansible_env.USER }}//anydesk_6.0.1-1_armhf.deb"

- name: Install anydesk
  apt: deb="/home/{{ ansible_env.USER }}/anydesk_6.0.1-1_armhf.deb"
