- name: Update all packages to their latest version
  apt: upgrade=dist force_apt_get=yes

- name: Install PIP3
  apt:
    name: python3-pip
    state: present

- name: Install Cheese
  apt:
    pkg:
    - cheese

- name: Install libreoffice
  apt:
    pkg:
    - libreoffice
    - libreoffice-gtk3 

- name: Install psutil
  pip:
    name: psutil

- name: fix themeing
  apt:
    pkg:
     - raspberrypi-ui-mods
     - libgdk-pixbuf2.0-dev

- name: install statistics gathering software
  apt:
    pkg:
    - acct

- name: Download anydesk deb 
  get_url: 
    url="https://download.anydesk.com/rpi/anydesk_6.0.1-1_armhf.deb"
    dest="/root/anydesk_6.0.1-1_armhf.deb"

- name: Install anydesk
  apt: deb="/root/anydesk_6.0.1-1_armhf.deb"

