- name: Install PIP3
  apt:
    name: python3-pip
    state: present

- name: Install libreoffice
  apt:
    pkg:
    - libreoffice
    - libreoffice-gtk3 

- name: Install psutil
  pip:
    name: psutil

- name: install statistics gathering software
  apt:
    pkg:
    - acct

- name: Download anydesk deb 
  get_url: 
    url="https://download.anydesk.com/rpi/anydesk_6.0.1-1_armhf.deb"
    dest="/root/anydesk_6.0.1-1_armhf.deb"

- name: Install anydesk
  apt: deb="/root/anydesk_6.0.1-1_armhf.deb"

- name: Copy ZOOM script
  copy:
    src: files/install_zoom.sh
    dest: /root/

- name: run zoom install script
  script: /root/install_zoom.sh
