- name: Install PIP3
  apt:
    name: python3-pip
    state: present

- name: Install psutil
  pip:
    name: psutil

- name: Install Gnome Flatpak support
  apt:
    pkg: 
    - gnome-software 
    - gnome-software-plugin-flatpak

- name: install statistics gathering software
  apt:
    pkg:
    - acct


- name: Install flatpak apps
  flatpak: 
    name: "{{item}}"
    state: present
    method: system
  with_items:
    - com.anydesk.Anydesk
    - us.zoom.Zoom

